virsh shutdown bootstrap
virsh undefine bootstrap
virsh shutdown master1
virsh undefine master1
virsh shutdown master2
virsh undefine master2
virsh shutdown master3
virsh undefine master3
virsh shutdown worker1
virsh undefine worker1
virsh shutdown worker2
virsh undefine worker2
virsh shutdown worker3
virsh undefine worker3
